# Generated by Django 2.0.1 on 2018-01-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='test test odmasiomd asmoidm aiosmd '),
            preserve_default=False,
        ),
    ]
